# Generated by Django 3.0 on 2019-12-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['name', '-age']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', '-age']},
        ),
    ]
