# Generated by Django 2.2.9 on 2019-12-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='mane',
            new_name='name',
        ),
    ]
