# Generated by Django 2.2.9 on 2019-12-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitable', '0003_auto_20191223_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant1',
            old_name='near_place',
            new_name='near_places',
        ),
    ]
